# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-13 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat_page',
            options={'verbose_name': 'Flat Page', 'verbose_name_plural': 'Flat Pages'},
        ),
    ]
