# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-15 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat_pages', '0002_auto_20170212_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat_page',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
