# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(default='', help_text='Full Name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', help_text='Full name', max_length=200)),
                ('abbreviation', models.CharField(default='', help_text='3 letter abbreviation', max_length=3)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Individual_Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.ManyToManyField(blank=True, related_name='_individual_winner_bronze_+', to='sports.Athlete')),
                ('gold', models.ManyToManyField(blank=True, related_name='_individual_winner_gold_+', to='sports.Athlete')),
                ('silver', models.ManyToManyField(blank=True, related_name='_individual_winner_silver_+', to='sports.Athlete')),
            ],
            options={
                'verbose_name': 'Winners for Individual Sport',
                'verbose_name_plural': 'Winners for Individual Sports',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(default='')),
                ('lock_date', models.DateField()),
                ('sport_description', models.TextField(default='Sport Description')),
                ('scoring', models.TextField(default='score')),
                ('favorite', models.TextField(default='favorites')),
                ('competition_dates', models.TextField(default='dates')),
                ('rankings_url', models.URLField(blank=True, help_text='The official website rankings list.')),
                ('winner_type', models.CharField(choices=[('IN', 'Individual'), ('TM', 'Team')], default='TM', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=False, help_text='All active will display.')),
                ('image_attribute', models.CharField(blank=True, default='', max_length=200)),
                ('image_source', models.URLField(blank=True, default='')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Team_Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.ManyToManyField(blank=True, related_name='_team_winner_bronze_+', to='sports.Country')),
                ('gold', models.ManyToManyField(blank=True, related_name='_team_winner_gold_+', to='sports.Country')),
                ('silver', models.ManyToManyField(blank=True, related_name='_team_winner_silver_+', to='sports.Country')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport')),
            ],
            options={
                'verbose_name': 'Winners for Team Sport',
                'verbose_name_plural': 'Winners for Team Sports',
            },
        ),
        migrations.AddField(
            model_name='individual_winner',
            name='sport',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country+', to='sports.Country'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='_athlete_sports_+', to='sports.Sport'),
        ),
    ]
