# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sports',
        ),
        migrations.AddField(
            model_name='athlete',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports+', to='sports.Sport'),
        ),
    ]
