# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-21 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20170220_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sports',
        ),
        migrations.AddField(
            model_name='athlete',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='_athlete_sports_+', to='sports.Sport'),
        ),
    ]
