# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-25 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_sport_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
