# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_sport_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_images',
            name='alt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
