# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-27 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0006_sport_images_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronze', models.ManyToManyField(blank=True, related_name='_winner_bronze_+', to='sports.Athlete')),
                ('gold', models.ManyToManyField(blank=True, related_name='_winner_gold_+', to='sports.Athlete')),
                ('silver', models.ManyToManyField(blank=True, related_name='_winner_silver_+', to='sports.Athlete')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport')),
            ],
            options={
                'verbose_name': 'Winners for Individual Sport',
                'verbose_name_plural': 'Winners for Individual Sports',
            },
        ),
        migrations.RemoveField(
            model_name='individual_winner',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='individual_winner',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='individual_winner',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='individual_winner',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='team_winner',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='team_winner',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='team_winner',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='team_winner',
            name='sport',
        ),
        migrations.DeleteModel(
            name='Individual_Winner',
        ),
        migrations.DeleteModel(
            name='Team_Winner',
        ),
    ]
