# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-04 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_auto_20170226_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winner',
            options={'verbose_name': 'Winner', 'verbose_name_plural': 'Winners'},
        ),
    ]
