# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-03-07 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_sport_award_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
