# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170212_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='/media/avatars/'),
        ),
    ]
