# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-07 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
