# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-11 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_extended_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended_user',
            name='notificatons',
            field=models.BooleanField(default=False),
        ),
    ]
