# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-11 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_extended_user_notificatons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extended_user',
            old_name='notificatons',
            new_name='notifications',
        ),
    ]
