# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170311_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended_user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
