# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-15 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commenting_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.TextField(default='')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('bronze', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze+', to='sports.Athlete')),
                ('gold', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold+', to='sports.Athlete')),
                ('silver', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver+', to='sports.Athlete')),
                ('sport', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport+', to='sports.Sport')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
