# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-21 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenting_on',
            options={'verbose_name': 'Comments Allowed', 'verbose_name_plural': 'Comments Allowed'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='guesses',
            options={'verbose_name': 'Guess', 'verbose_name_plural': 'Guesses'},
        ),
    ]
