# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-22 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_participation', '0002_auto_20170220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesses',
            name='gold',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
