# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-23 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_participation', '0004_auto_20170221_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guesses',
            name='bronze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bronze+', to='sports.Athlete'),
        ),
        migrations.AlterField(
            model_name='guesses',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold+', to='sports.Athlete'),
        ),
        migrations.AlterField(
            model_name='guesses',
            name='silver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silver+', to='sports.Athlete'),
        ),
    ]
