# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-09-20 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_participation', '0007_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updates',
            options={'verbose_name': 'Updates', 'verbose_name_plural': 'Updates'},
        ),
    ]
